### ISSUE TITLE
Inoperative proprietor

### ISSUE THREAD

**Issue by Mosterdt** [anthonyclays/Mazub#2]
Please hand this project over to someone else. You're behavior is coming out of the scuppers. It hurts my eyes to see such a lovely idea being *crushed* by your ineptitude.

**Comment by Mosterdt** [comment]
Also you got issues

**Comment by anthonyclays** [comment]
s/You're/Your/

'ineptitude' seems relevant indeed

**Comment by Mosterdt** [comment]
You win this one

but you haven't won the war.
